### ISSUE TITLE
buggy behavior in selection

### ISSUE THREAD

**Issue by dawoodalbadi** [HOST-Oman/scribus#10]
![screenshot from 2016-02-23 21 27 40](https://cloud.githubusercontent.com/assets/9442944/13260424/cf086b72-da74-11e5-8584-68534b3fd9a0.png)

**Comment by khaledhosny** [comment]
Please mention the commit id that fixed this.

**Comment by dawoodalbadi** [comment]
8c97f3dcb59179f4b70eb8ef13c91c3329bb346f
