### ISSUE TITLE
older version of harfbuzz so appimage can build on CentOS 6

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#104]
@probonopd writes:

```
I tried compiling the CTL branch. 
It requires relatively recent versions of harfbuzz
 (which requires relatively recent version of glib) 
which is a real pain to compile on CentOS 6.

# -- checking for modules 'harfbuzz>=0.9.38;harfbuzz-icu'
# -- package 'harfbuzz>=0.9.38' not found
# -- package 'harfbuzz-icu' not found

Could the dependency be relaxed to an older version of harfbuzz, e.g., 0.9.8, 
which compiles on CentOS 6 without much hassle?
```

**Comment by probonopd** [comment]
I am working on a [script](https://github.com/probonopd/AppImages/blob/master/recipes/scribusctl/Recipe) that builds the CTL branch on CentOS 6. Please feel free to chime in.
Objective is to get it to compile on CentOS 6. The normal branch builds on CentOS 6 fine using this [script](https://github.com/probonopd/AppImages/blob/master/recipes/scribus/Recipe).

**Comment by Fahad-Alsaidi** [comment]
CentOS 6 is very old system and used for servers mainyly not Desktops.  I
prefer to build packages for Fedora.

**Comment by probonopd** [comment]
The reason why I want to build on CentOS 6 is to create an [AppImage](http://appimage.org) that runs (almost) everywhere. For this to work, we need to compile on an old build system.

**Comment by khaledhosny** [comment]
We are going to require even more recent HarfBuzz actually as we need APIs not present in older versions. Using older HarfBuzz can provide user experience since there might be new features we need or even bug fixes. I don’t know anything about AppImage, but the solution here is usually not using the system HarfBuzz and just statically linking a new version (and I always recommend the latest and greatest HarfBuzz.

**Comment by khaledhosny** [comment]
It seems that your problem is with GLib version, but we don’t user HarfBuzz’s GLib support so you can just build with GLib disabled.

**Comment by luzpaz** [comment]
@probonopd that should solve it then, to build without glib support

**Comment by probonopd** [comment]
Will try `./configure --prefix=/usr --with-gobject`
