### ISSUE TITLE
Buggy behaviour in hyperlinks (export to pdf)

### ISSUE THREAD

**Issue by dawoodalbadi** [HOST-Oman/scribus#11]
when exporting text to pdf I notice that sometimes hyper-link underline is not correct

**Comment by khaledhosny** [comment]
Please elaborate on the issue.

**Comment by dawoodalbadi** [comment]
not a bug, it is svn feature

**Comment by khaledhosny** [comment]
A feature in what sense, can we find out which character style was used?

**Comment by dawoodalbadi** [comment]
I don't know, may be I confused you when I said feature(may be it a bug).
If you remember the file when we noticed this bug, I run the same file in
svn version and I get similar to what we get in boxes branch, so it is not
our problem 😊

**Comment by khaledhosny** [comment]
I figured that, but I think we still need to investigate it and understand what is going on.
