### ISSUE TITLE
Building CTL on OSX using homebrew

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#117]
This is a way to streamline building the Host-Oman CTL branch using Homebrew Package Manager:
- install homebrew
- type: `brew update && brew upgrade --all`
- type: `brew install --HEAD https://gist.githubusercontent.com/luzpaz/1712c7e3142e1edb3e17/raw/scribushostctl.rb --verbose`
- invoke from CLI by typing: `/usr/local/Cellar/scribushostctl/HEAD/Scribus.app/Contents/MacOS/Scribus` and press `enter`

**Comment by khaledhosny** [comment]
I think this should be moved somewhere, the GitHub wiki may be?
