### ISSUE TITLE
subscript/superscript positions are not correct in PDF

### ISSUE THREAD

**Issue by dawoodalbadi** [HOST-Oman/scribus#12]
![screenshot from 2016-02-24 22 44 42](https://cloud.githubusercontent.com/assets/9442944/13296751/7d609a4a-db48-11e5-805f-c2f3165a3514.png)

**Comment by khaledhosny** [comment]
The superscripts are too high as well.

**Comment by dawoodalbadi** [comment]
solved by https://github.com/HOST-Oman/scribus/commit/06a8687eb84bdc93e1f929268fb9b1e997115080 and https://github.com/HOST-Oman/scribus/commit/4354bfc23e81cd54d116cf2763743759eef62f5c
