### ISSUE TITLE
manual tracking for characters does not work

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#130]
When you set manual tracking for chars it does not work.

**Comment by Fahad-Alsaidi** [comment]
@khaledhosny I found this in layout() function:
`//TODO: cjk spacing and kerning should be done in layoutGlyphs!`

could you elaborate more about this point ?

**Comment by khaledhosny** [comment]
I don’t think this is related, the code this comment refers to is CJK specific. I’ll try to look into this issue and #141 as well.

**Comment by Fahad-Alsaidi** [comment]
Last time I checked the code, all kerning code was removed from layout code
including CJK kerning.

**Comment by khaledhosny** [comment]
The so called CJK kerning is not kerning in the usual sense (it does not depend on the font) but special spacing rules to be applied to CJK ideographs and this code is definitely there, but untested. We need someone to test CJK functionality (line breaking, spacing) and report what works and what doesn't as we didn’t do any testing of this area at all. I opened #143 for that.

**Comment by khaledhosny** [comment]
Should be fixed now, please test.

**Comment by Fahad-Alsaidi** [comment]
I can confirm that it fixed.
@luzpaz  please test.
