### ISSUE TITLE
Explore doing proper Arabic justification

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#135]
We currently don’t do any special Arabic justification, but proper Arabic justification requires kashida insertion, alternate glyphs substitutions and other considerations. This can be done independent of #134, but it might be better to be on top of it.

**Comment by zayedalsaidi** [comment]
Here is some papers about this subject for brave programmers 
1- [Arabic text justification](https://www.tug.org/TUGboat/tb27-2/tb87benatia.pdf)
2- [Justify Just or Just Justify](http://quod.lib.umich.edu/j/jep/3336451.0013.105/--justify-just-or-just-justify?rgn=main;view=fulltext)

Good luck
