### ISSUE TITLE
Make Scribus faster and more efficient

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#136]
Currently many parts of Scribus are unnecessarily slow, many tasks are done repeatedly for not good reason and almost no caching of any sorts is happen. We should profile common tasks, find the bottle necks and figure out what is the best way to optimize it. This is no small project as it will likely require big changes and rewrites to make the code efficient.

**Comment by luzpaz** [comment]
- [ ] [12825](https://bugs.scribus.net/view.php?id=12825) **Severe performance issue with layers**
- [ ] [9672](https://bugs.scribus.net/view.php?id=9672)
- [ ] [9826](https://bugs.scribus.net/view.php?id=9826) **images load twice during opening SLA file when CMS enabled**

**Comment by Fahad-Alsaidi** [comment]
Here is the [output](https://github.com/HOST-Oman/scribus/files/244503/output.txt.zip) of: 
`valgrind --leak-check=full --show-reachable=yes --log-file=output.txt ./scribus
`
if anyone interested into looking in this project.
