### ISSUE TITLE
Add more language to the LanguageManager

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#138]
Since we use the language for OpenType processing, we should expand the list of languages to at least the languages we know are working correctly.

**Comment by luzpaz** [comment]
What do you mean language manager? 
Pasting these here for reference 
- https://bugs.scribus.net/view.php?id=11453
- https://bugs.scribus.net/view.php?id=7153

**Comment by khaledhosny** [comment]
LanguageManager is the class that handles languages exposed in the language drop down lists, adding a new language there allows selecting it in character styles etc.

**Comment by khaledhosny** [comment]
We need to compile a list of languages that we should add (based on bug reports etc.), @luzpaz can you help with that?

**Comment by luzpaz** [comment]
Sure thing.

**Comment by luzpaz** [comment]
Reference: 
Current languages are listed in: 
- scribusproject/scribus master branch https://github.com/scribusproject/scribus/blob/e664063916f8dea9fc8e48864caa2fc6b4597b8a/scribus/langmgr.cpp#L91-L173
- HOST-Oman/scribus ctl branch: https://github.com/HOST-Oman/scribus/blob/ctl/scribus/langmgr.cpp#L92-L175

**Comment by luzpaz** [comment]
- [x] Afrikaans (af / af_ZA)
- [x] Albanian (sq / )
- [x] Anii (blo / )
- [x] Arabic (ar / )
- [x] Aragonese (an_ES / )
- [x] Basque (eu / )
- [x] Belarusian (be_BY / )
- [x] Bengali (bn / )
- [x] Bengali (Bangladesh) (bn_BD / )
- [x] Bosnian (bs_BA / bs_BA)
- [ ] Breton (br / br_FR)
- [x] Bulgarian (bg / bg_BG)
- [x] Catalan (ca / )
- [x] Chinese (zh / )
- [x] Chinese (Trad.) (zh_TW / )
- [x] Croatian (hr / )
- [x] Czech (cs / cs_CZ)
- [x] Danish (da / da_DK)
- [x] Dutch (nl / nl_NL)
- [x] Dzongkha (dz / )
- [x] English (Australia) (en_AU / )
- [x] English (Canada) (en_CA / )
- [x] English (New Zealand) (en_NZ / )
- [x] English (South Africa) (en_ZA / )
- [x] English (UK) (en_GB / en)
- [x] English (US) (en_US / )
- [x] Esperanto (eo / )
- [x] Estonian (et / et_EE)
- [x] Finnish (fi / )
- [x] French (fr / fr_FR)
- [x] Galician (gl / gl_ES)
- [x] German (de / de_DE)
- [x] German (Austria) (de_AT / )
- [x] German (Swiss) (de_CH / )
- [x] German (Trad.) (de_1901 / )
- [x] Greek (el / )
- [x] Gujarati (gu / gu_IN)
- [x] Hebrew (he / he_IL)
- [x] Hindi (hi_IN / )
- [x] Hungarian (hu / hu_HU)
- [x] Icelandic (is / )
- [x] Indonesian (id / )
- [x] Italian (it / it_IT)
- [x] Japanese (ja / )
- [x] Kabyle (kab / )
- [x] Kannada (kn_IN / )
- [x] Khmer (km / )
- [x] Korean (ko / )
- [x] Kurdish (ku / )
- [x] Lao (lo / )
- [x] Latin (ia / )
- [x] Latin (la / )
- [x] Lithuanian (lt / lt_LT)
- [x] Luxembourgish (lb / )
- [x] Mongolian (mn_MN / )
- [x] Nepali (ne_NP / )
- [x] Norwegian (no / no_NO)
- [x] Norwegian (Bokmål) (nb / nb_NO)
- [x] Norwegian (Nnyorsk) (nn / nn_NO)
- [x] Persian (fa_IR / )
- [x] Polish (pl / pl_PL)
- [x] Portuguese (pt / pt_PT)
- [x] Portuguese (BR) (pt_BR / )
- [x] Romanian (ro / )
- [x] Russian (ru / ru_RU)
- [x] Sanskrit (sa / )
- [x] Scottish Gaelic (gd / gd_GB)
- [x] Serbian (sr / )
- [x] Serbian (Latin) (sr-Latn / sr-Latn)
- [x] Slovak (sk / sk_SK)
- [x] Slovenian (sl / sl_SL)
- [x] Somali (so / )
- [x] Spanish (es / es_ES)
- [x] Spanish (es / es_ANY)
- [x] Spanish (Argentina) (es_AR / )
- [x] Spanish (Latin) (es_LA / )
- [x] Swedish (sv / )
- [x] Telugu (te / te_IN)
- [x] Thai (th / th_TH)
- [x] Turkish (tr / tr_TR)
- [x] Ukranian (uk / uk_UA)
- [x] Urdu (ur / )
- [x] Vietnamese (vi / )
- [x] Welsh (cy / cy_GB)

**Comment by Fahad-Alsaidi** [comment]
right now language list contains 83 languages. I can add more based on [this complied list](https://www.microsoft.com/typography/otspec/languagetags.htm) but this will make a huge list which makes things difficult. So I prefer to close this and open a new bug for each new language.

**Comment by khaledhosny** [comment]
I tend to agree here, but I’ll wait if @luzpaz can find any languages requested/reported unsupported before that we can add them. A long list is not a problem though, if we keep it sorted alphabetically. May be we can also make it a combobox and allow entering arbitrary language code (like LibreOffice done relatively recently), but this will need some changes to how languages are handled internally.

**Comment by luzpaz** [comment]
So Scribus has been adding languages based on if they have a translation of the UI. 
How do we reconcile languages that haven't been translated for Scribus ?

**Comment by khaledhosny** [comment]
There are two different uses of the language list and here we are mostly talking about using it to influence the typesetting, so whether Scribus is translated for a given language or not is not much relevant. I think we should go with my suggestion in https://github.com/HOST-Oman/scribus/issues/138#issuecomment-208358624 so that any arbitrary language tag can be used.

**Comment by luzpaz** [comment]
yea, go for it.

**Comment by khaledhosny** [comment]
OK, closing this as #146 should cover us for now.
