### ISSUE TITLE
Support non-standard hyphenation

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#145]
See http://hunspell.sourceforge.net/tb87nemeth.pdf. The libhyphen library Scribus is using already supports this, but Scribus does not make use of this support.

**Comment by gyuris** [comment]
@khaledhosny, see this feature request upstream: https://bugs.scribus.net/view.php?id=3159

**Comment by gyuris** [comment]
Implemented?

**Comment by khaledhosny** [comment]
Nope. I’m closing staled issues I opened that I’m not interested in anymore.

**Comment by aoloe** [comment]
Sad.

**Comment by khaledhosny** [comment]
Just to be clear, I haven’t been working on this Scribus fork and had no interest in Scribus development for a long time now. I’m closing this issue because it was reported by me, but anyone interested in the subject or wants to work on it can open a new issue.

**Comment by aoloe** [comment]
Jut to be clear: all of this is sad and I don't think you have any fault in it.
