### ISSUE TITLE
Fix text selection problem 

### ISSUE THREAD

**Issue by dawoodalbadi** [HOST-Oman/scribus#15]
I tried boxes branch in many devices and I found out that when low performance machine used, selection is very buggy and slow. So this is very critical issue we didn't take care of it.  This problem is related to buggy behavior of cursor movement I think it is happen by wrong measurement of bounding box and when you click in position between 2 boxes it doesn't recognize the place and move the cursor to the end of the frame. This is just theory need to be test.

**Comment by khaledhosny** [comment]
cc @ibtisamN

**Comment by khaledhosny** [comment]
Should be fixed with 7c0b5dc7c82c84be09556893df55e72b7ad3071f. Opened #20 for the remaining issue with selection.
