### ISSUE TITLE
can't save to linked text frames

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#150]
How to produce it:
1- make text frame that small enough to not fit two  30pt words in it. 
2- type two word and make sure to make the text frame has text overflow 
3- click on small red square in right down of the text frame to create a new text frame. something likes this:
![scribus-linked frames](https://cloud.githubusercontent.com/assets/1632566/14566430/a23c7b66-0340-11e6-8718-47db65c74641.jpg)

4- then try to save the file.

**Comment by Fahad-Alsaidi** [comment]
Here is a test file. Try to save it to produce the bug.
[linkedframe.sla.gz](https://github.com/HOST-Oman/scribus/files/222499/linkedframe.sla.gz)

**Comment by Fahad-Alsaidi** [comment]
I did bisect and I found the problem started from this commit 32b1462e83bbb6fb398304c8f716946d1128a322

**Comment by khaledhosny** [comment]
I still can’t reproduce this, the attached document saves fine for me.

**Comment by aoloe** [comment]
i also cannot reproduce...

**Comment by Fahad-Alsaidi** [comment]
I figure out the problem thanks for @asmaAL-Bahanta  for help. closed.

**Comment by khaledhosny** [comment]
So what was the problem?

**Comment by Fahad-Alsaidi** [comment]
well, there was a missing "make install " step in my Qcreator project setup.
