### ISSUE TITLE
We should not reshape text for linked text frames

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#155]
Currently we reshape the text from the first character in the frame text the end of story text for each frame, which can be slow for very long text. We should instead shape the text only once per story text and share the shaped glyphs between text frames sharing the same story text.

**Comment by khaledhosny** [comment]
Shaping text only once will not work as the shaping needs to know the current item. A different approach is to split the text on paragraph boundaries and do the shaping incrementally.

**Comment by andreas-vox** [comment]
I'm working on a solution that will cache shaped text in StoryText and only reshape during layout if it is needed (basically pagenumbers and marks).

I'll also split shaping per paragraph, so the layouter will only shape the parts it needs not the whole linked story.

**Comment by khaledhosny** [comment]
Wonderful, looking forward to it. This is the last major issue remaining for CTL branch.

**Comment by Fahad-Alsaidi** [comment]
Testing doc contains 100 page. It is very slow to browse and edit.
[longdoc.sla.gz](https://github.com/HOST-Oman/scribus/files/265666/longdoc.sla.gz)

**Comment by andreas-vox** [comment]
This issue should be fixed by now

**Comment by Fahad-Alsaidi** [comment]
fixed and tested in latest commits. Thanks @andreas-vox  for his great work.
