### ISSUE TITLE
Too long time to open a large file

### ISSUE THREAD

**Issue by ftake** [HOST-Oman/scribus#157]
Scribus CTL takes much more time to layout texts than Scribus 1.5.1.

To open the following document, it takes two minutes on my old laptop (Core 2 Duo U9400).
[long-japanese-document.zip](https://github.com/HOST-Oman/scribus/files/226214/long-japanese-document.zip)

**Comment by ftake** [comment]
Here is the result of `perf` obtained on another machine (VirtualBox + Core i7-3770S + 8 GB Mem.)

```
Overhead  Command          Shared Object                   Symbol                                                                                                     
  71.21%  scribus          libc-2.22.so                    [.] __memcpy_sse2_unaligned
   0.82%  scribus          libc-2.22.so                    [.] _int_malloc
   0.75%  scribus          ld-2.22.so                      [.] _dl_sort_fini
   0.61%  scribus          liblcms2.so.2.0.7               [.] cmsEvalToneCurveFloat
   0.50%  scribus          libc-2.22.so                    [.] _int_free
   0.49%  scribus          [unknown]                       [k] 0xffffffff81003228
   0.45%  scribus          libc-2.22.so                    [.] __strcmp_sse2_unaligned
   0.42%  scribus          libfreetype.so.6.12.3           [.] 0x000000000006ce98
   0.40%  scribus          libc-2.22.so                    [.] malloc
   0.39%  scribus          [unknown]                       [k] 0xffffffff816cb925
   0.34%  scribus          libQt5Core.so.5.5.1             [.] QCoreApplication::removePostedEvents
```

**Comment by khaledhosny** [comment]
This needs to be profiled to find why we are spending so much time in memcpy. Valgrind’s callegrind should be good if someone wants to do it.

**Comment by Fahad-Alsaidi** [comment]
Here is Valgrind’s callegrind output file
[callgrind.tar.gz](https://github.com/HOST-Oman/scribus/files/233333/callgrind.tar.gz)
 for reviewing.

However, the problem appears in this call FT_Load_Sfnt_Table in referenceTable(). It consumes more than 49% of total time.

**Comment by khaledhosny** [comment]
Something wrong is going here, we are calling `hb_shape` almost 1000 times per each `TextShaper::shape()` call, I’m guessing something is wrong with the itemisation, and since we are dealing with Japanese here it might be because the different Japaneses scripts are itemised separately.

**Comment by khaledhosny** [comment]
I still don’t understand why `referenceTable` are called so many times, may be because we don’t cache our HarfBuzz faces?

**Comment by khaledhosny** [comment]
OK, most of this time is spent in `hb_ot_font_set_funcs()`, so if we moved the code in https://github.com/HOST-Oman/scribus/blob/ctl/scribus/text/textshaper.cpp#L343-L363 to ScFace class and added a new `hbFont()` method there that would create the `hb_font_t` just once, then we would be calling that code only once per `ScFace` instance instead of calling it for each text run we are shaping. This would even help alleviate #156 even if the leak is not fixed.

**Comment by khaledhosny** [comment]
With 328cf8b8002240c3e9e932c71916860c6c5d2739, this file loads almost instantly on my machine. The remaining slowness might be related to #155.

**Comment by khaledhosny** [comment]
I just pushed c533c03 with improves shaping even further.

**Comment by Fahad-Alsaidi** [comment]
I can confirm that the attached file open quick enough in my laptop. @ftake please test & confirm to close this bug.

**Comment by ftake** [comment]
I confirmed this problem was resolved. Thank you.
