### ISSUE TITLE
Background color for selected text not working

### ISSUE THREAD

**Issue by dawoodalbadi** [HOST-Oman/scribus#16]
its new option which was added when we were work on unupdated version

**Comment by khaledhosny** [comment]
I think we need to add away for boxes to render a background colour.

**Comment by dawoodalbadi** [comment]
I didnt look to the new codes for background but I think every thing is good and we need to modify pageitem_texstframe drawitemopj as we did befor. To make that we need a new flag only and set the code accordingly. What you Think @khaledhosny ??

**Comment by khaledhosny** [comment]
I think we need to find out how the new code works then decide what is the best way to fit it in the new model. I suspect it currently works similar to how text selection is drawn, so may be we can find a way to handle both in a similar way.

**Comment by dawoodalbadi** [comment]
Fixed with https://github.com/HOST-Oman/scribus/commit/2193f27d029e81bf305967c3e5a5d81753029577
