### ISSUE TITLE
Regression in support CTL in DrawText()

### ISSUE THREAD

**Issue by zayedalsaidi** [HOST-Oman/scribus#165]
It seem there is a regression in CTL support in DrawText()
![draw-text-reg](https://cloud.githubusercontent.com/assets/18646956/14796814/57e4b8c8-0b40-11e6-995c-9abb18a808d3.png)

The test file here:
[ctl-drawtext.sla.tar.gz](https://github.com/HOST-Oman/scribus/files/235293/ctl-drawtext.sla.tar.gz)

**Comment by khaledhosny** [comment]
Not exactly a regression, but lack of support for font fallback in the new implementation of drawText, so if your GUI font does not have Arabic characters you will get empty boxes. I don’t think there is an easy way to fix this with current code.

**Comment by khaledhosny** [comment]
To expand, this code uses Cairo but Cairo does not have a usable high level text API. We are using now the same code that Scribus uses to typeset text and it does not support font fallback intentionally. We need to either support font fallback in `TextShaper::shape()` or find a usable Qt API that we can use here.

**Comment by zayedalsaidi** [comment]
As CTL user, the font fallback is a must for mix text. Just imagine you are writing a text contain 3 languages Thai, Arabic and English, good luck to find one font support all that languages.

**Comment by khaledhosny** [comment]
Indeed, that is why we have #110 for that. But it is not a simple task.

**Comment by zayedalsaidi** [comment]
Thank you. I think we should close this as duplicate of #110.
