### ISSUE TITLE
CJK justification does not work

### ISSUE THREAD

**Issue by ftake** [HOST-Oman/scribus#169]
CJK justification which was implemented in 1.5.0 does not work with CTL branch
- https://bugs.scribus.net/view.php?id=10292
- https://bugs.scribus.net/view.php?id=12928

Some spaces exist at the end of line.

Test data is attached to #143

**Comment by khaledhosny** [comment]
This is probably the same underlying issue as #170.

**Comment by khaledhosny** [comment]
I pushed a commit that should fix this, please test.

**Comment by ftake** [comment]
It looks working fine. Thanks!

**Comment by Fahad-Alsaidi** [comment]
I don't think it fixed completely see this screen shot:
![cjk](https://cloud.githubusercontent.com/assets/1632566/15050209/5714385e-1303-11e6-9b70-fd0b4493f42a.jpg)

**Comment by ftake** [comment]
I guess the problem with the first line is caused by the rule that the space of "「" is removed.

The problem with the last line looks similar to justification problem of line that have new line (not new paragraph), which exists before 1.5.1.

**Comment by khaledhosny** [comment]
@Fahad-Alsaidi are you using regular or full justification in this screenshot?

**Comment by Fahad-Alsaidi** [comment]
@khaledhosny full justification

**Comment by khaledhosny** [comment]
OK, so the last line is what I’d expect in full justification, the first line looks like a bug that needs to be investigated. Might be that the space we subtracted from “「” got added again.

**Comment by khaledhosny** [comment]
This should be fixed now, please test.

**Comment by ftake** [comment]
looks good to me

**Comment by khaledhosny** [comment]
Thanks for testing.
