### ISSUE TITLE
CJK: Implicit spacing between CJK and Latin does not work

### ISSUE THREAD

**Issue by ftake** [HOST-Oman/scribus#170]
Between CJK and Latin words, 1/4 spaces have been inserted implicitly since Scribus 1.5.0 (or 1.4.x). However, it does not work with CTL branch.
### Note 1

Like LibreOffice Writer's `Paragraph Style` > `Asian Typography` > `Apply spacing between  Asian, Latin and complex text`, It is better that this implicit spacing can be turned off with paragraph style because we sometimes do not need this spacing, for example, while writing source code.
### Note 2

The width of implicit spacing may change for justification like normal spaces, which was not implemented in 1.5.1 (bug).
### Other info

Test data is on #143 

The infomation used to impliment at the first time was here:
https://sites.google.com/a/borndigital.jp/scribus/scribus-en/line-composition

**Comment by khaledhosny** [comment]
I was expected this since it seems the code that flags possible implicit space insertion was removed early in the development of boxes model and no replacement was made, I’ll give it a look.

**Comment by khaledhosny** [comment]
Has this been fixed or is it still there?

**Comment by khaledhosny** [comment]
Found the root of the issue, please test and reopen if you think this is not fixed.

**Comment by ftake** [comment]
looks the same with 1.5.1 (in both good and bad points)

**Comment by khaledhosny** [comment]
I’d like to fix the bad points if you can list them.
