### ISSUE TITLE
cursor postion not correct

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#174]
after last commit https://github.com/HOST-Oman/scribus/commit/7dce89eb1a76e77e8a552f098cb12687dea6b425 there are two bad behaviors appeared: 
1- when move to next char by key ( right or left key depends on RTL or LTR) it keeps looping the word. You can notice that when there is a one word in text frame.
2. You can't put the cursor before last char by mouse clicks. It goes to the end of the word.

**Comment by khaledhosny** [comment]
Should be fixed now, please test.

**Comment by Fahad-Alsaidi** [comment]
The first part fixed, still the second part.

**Comment by khaledhosny** [comment]
I can’t reproduce the second one, please attach a screen cast showing the issue.

**Comment by Fahad-Alsaidi** [comment]
have a look here:
https://www.dropbox.com/s/svcviflhszr4a23/vokoscreen-2016-05-05_12-06-14.mkv?dl=0

It seems it also affects the selection

**Comment by khaledhosny** [comment]
Should be fixed now, please test.

**Comment by Fahad-Alsaidi** [comment]
fixed. Thanks.
