### ISSUE TITLE
Setting strike through makes most of the text disappear

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#179]
Here is a test document:
[strikethrough.sla.gz](https://github.com/HOST-Oman/scribus/files/252643/strikethrough.sla.gz)

**Comment by khaledhosny** [comment]
We need to bisect this and see why it was broken. @Fahad-Alsaidi can you work on that?

**Comment by Fahad-Alsaidi** [comment]
sure.

**Comment by Fahad-Alsaidi** [comment]
The bad behavior started from this 55c20a8e2e2b83f374be89dbf43d674d03f878c2

In this stage text doesn't disappear yet. Just half disappeared.

**Comment by Fahad-Alsaidi** [comment]
The text disappears totally from this commit  6aea2c1c19abbc180421fd516699d32d1c94821f

**Comment by khaledhosny** [comment]
Thanks @Fahad-Alsaidi, will investigate. Seems weird!
