### ISSUE TITLE
Help Translate Scribus UI in to CJK/RTL/NLS languages

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#182]
Interested in helping to translate the Scribus User Interface?
1. Go to our Transifex translation repo (https://www.transifex.com/scribus/scribus)
2. Sign up by pressing on HELP TRANSLATE "Scribus" button
3. Choose the language that you want to translate (make sure to browse all available languages before requesting to translate a new one

Thanks!

(this isn't a bug per se but more like a heads-up)

**Comment by aoloe** [comment]
Somebody is proposing to contribute to the Arabic translations for the Scribus UI.

Is there any interest?
How should I / she / he proceed?

**Comment by Fahad-Alsaidi** [comment]
All translations should go through upstream  scribus channel. It will come
here eventually.

**Comment by aoloe** [comment]
yes, fahad, that's clear!
but you might already have plans on translating the UI to arab... that's why i'm asking here first :-)

**Comment by Fahad-Alsaidi** [comment]
No, I prefer it to be there unless it's broken there.

**Comment by Fahad-Alsaidi** [comment]
I am closing this since [upstream](https://github.com/scribusproject/scribus-translations/issues/1) taking care about it.
