### ISSUE TITLE
Implement font preview in font list

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#186]
This feature will make scribus typesetting process more productive and will save a lot of clicks.

**Comment by aoloe** [comment]
i don't know, for many people browsing fonts for inspiration or picking a specific font to be used seem to be two different tasks.
scribus is aimed at professional users (by the word of the team...), people who are supposed to know how the name of a font relates to its visual appearance.

the scribus UI is generally speaking rather distracting, and having the fonts preview in the PP would imo be one more graphic element on the screen.

i would prefer the feature to go into "extras > font preview"
- allow the preview of the font in the list, as you want in the PP / styles manager
- with a button that turns on / off the preview of the font in the fonts list itself
- making the "big" demo text facultative (the default being to preview the font in the list itself or by applying it to the selected frame, if any)
- by making the "font preview" really non-modal (it should be a "palette" like all the others one... possibly with horizontal and vertical layout)
- add a preview button (that starts the "font preview") to the places where one can pick a font (the alternative way of browsing fonts should be very visible).
  (we should generally have buttons to manage resources next to the places where they can be selected)
- possibly rename the "font preview" in "fonts browser" to better match its use (people do not want to preview the fonts, they want to browse fonts :-)

being able to easily browse and preview fonts is something i'd really want to have in scribus... but i think i prefer the fonts list to be as unimpressive as it currently is... (but with a text filter for easily fast selection of the font i'm looking for)

**Comment by khaledhosny** [comment]
I think Fahad is talking about font preview similar to MS Word; when you
hover over a font on the list, the text that the font would apply to
changes temporarily to that font, when you hover away it reverts back.

**Comment by aoloe** [comment]
like this?

https://www.youtube.com/watch?v=E-fMDfIFBSU

preview on hover: why not?

but even then... having a fancy "fonts browser" that is easy to discover + easy to use gets my preference.
and keeping the widget in the PP as simple/small as possible (many people have to follow some sort of "corporate identity" most of the time... and there is not that much of freedom when switching fonts...)

**Comment by Fahad-Alsaidi** [comment]
Well, I  am talking about the baisc font preview in the font combo list. It is implemented in every decent DTP except scribus. It is a exaggeration to assume that _ALL_ scribus are or will be professionals. As similar to other source softwares, it should be easy to use for unprofessional, people who don't have money to hire a professional.

The second stage of this feature will be a _Live_ font preview as Khaled explained.

**Comment by khaledhosny** [comment]
I think live preview (even for all styles not just font) is much more useful than putting some sample text in the font combo box. I agree with @aoloe that it just clutters the UI and it is often of limited usefulness: If a font has Latin and Arabic, which to show? Cyrillic and Arabic? Greek and Armenian? Arabic, Latin, Cyrillic, Syriac, …? What to do with fonts that lie about languages they support (reading the cmap table to find the actual coverage is expensive)? etc. Other applications rarely get it right anyway.

**Comment by aoloe** [comment]
@Fahad-Alsaidi of course not all scribus users are professional graphics designers! (i for one am not :-)
probably, most are not.

but one of the few official statement from the team about scribus is that they are targeting professional users.

in the past, we have tried to introduce personas in order to better define / understand what the priorities are, but it never really caught.
so, that's the best i have for justifying my opinions :-)

anyway, when i comment about a modification, i try to first to make sure that it fits the needs of professional users in a professional setting and then -- of course! -- make sure that it's friendly to all users (which mostly makes it better anyway).
but i prefer to avoid changes that get in the way of professional users. (and going the other way -- making beginner friendly features fit professional users -- is less likely to lead to excellence)

**Comment by Fahad-Alsaidi** [comment]
Ok, I address all of your concerns. 

> If a font has Latin and Arabic, which to show? Cyrillic and Arabic? Greek and Armenian? Arabic, Latin, Cyrillic, Syriac, …?

It will show all Writing system supported by the font.  However, this is not required because there are a few fonts that support more than 4 languages and meant to be use in typesetting such as DejaVu Sans & FreeSans.

> What to do with fonts that lie about languages they support (reading the cmap table to find the actual coverage is expensive)?

This will not be our problem. In my proposal I am using QFontDatabase. 

> Other applications rarely get it right anyway.

This is not an excuse to not implement it. This feature will help a lot of scribus users especially the new users using Story text editor.

For professional users, I propose the following:
- Now it is possible just type font name in font combo box and set it without the need to choose the font from the droplist.
- In story text editor,  Search&Replace and Item Tools, the font list renders with font styles name to get the right font & style.

**Comment by Fahad-Alsaidi** [comment]
I welcome any feedback.
![fontpreview](https://cloud.githubusercontent.com/assets/1632566/15281047/9a8a3bea-1b48-11e6-8c30-b79faa060a3c.jpg)

**Comment by MrB74** [comment]
Very nice!!!

**Comment by luzpaz** [comment]
![0013314-mockup-default-font-sorting](https://cloud.githubusercontent.com/assets/4140247/15305953/342b65d8-1b8c-11e6-806a-caf59aeb442c.png)
Just planting a seed here regarding [13314](https://bugs.scribus.net/view.php?id=13314) ""Default" styles should stay on top of the list regardless of alphabetical sorting"

**Comment by khaledhosny** [comment]
I didn’t check the code, but the screenshot is very cluttered. This is definitely not how I’d want this. Just showing every script the font supports just makes things worse not better.

**Comment by Fahad-Alsaidi** [comment]
@khaledhosny what about to limit the samples to 3 including Latin script?  Most professorial fonts don't support more than 3 languages. 

@luzpaz It is a good idea. Let's agree on font preview concept then I can move to next issue.

**Comment by MrB74** [comment]
Thats styles though, not fonts in the font list. Although the last 3 used at the top is useful.

**Comment by khaledhosny** [comment]
Three scripts is still too much, besides which three scripts we are going to select? One of the reason I prefer MS Word-style previews is that the UI is less intrusive while being highly relevant as one can see how the font looks like on the text he is actually working on, not some random text for a selection of scripts of our choice.

I think we need first to identify what is the sort of UI we want here, by e.g. checking what relevant applications do (MS Word, LibreOffice Writer, InDesign, etc.) and agree on some mockup before doing the actual implementation.

**Comment by Fahad-Alsaidi** [comment]
well,  here is MS word:
![ms fontpreview](https://cloud.githubusercontent.com/assets/1632566/15383682/fa841da4-1da5-11e6-8f18-271d14fe252d.png)

here is Quark Xpress:
![quarkexpress](https://cloud.githubusercontent.com/assets/1632566/15383689/088d396c-1da6-11e6-868a-976ad005291d.png)

Here is LibreOffice:
![fontpreview-libreoffice](https://cloud.githubusercontent.com/assets/1632566/15383690/08b3cf46-1da6-11e6-820d-e4230ed68d16.jpg)

Here is Adobe Indesign 
![fontpreview-indesgin](https://cloud.githubusercontent.com/assets/1632566/15383692/08f17da0-1da6-11e6-9b50-4ab544d3cb52.jpg)

**Comment by MrB74** [comment]
I think this is something that more people should be involved in. However maybe that basics of preview generation can work for all versions.

**Comment by zayedalsaidi** [comment]
I think we need usability expert here.

**Comment by aoloe** [comment]
personally, i tend to stick to my opinion: a plain font picker for the PP and a fancy one (with options?) for the fonts browser.
i still believe that discovering fonts (and needing a preview) is a different task (done at a different time in the workflow) than applying a font.

i can live with the ID solution, but the others one are more disturbing than useful to me.
(i guess that the ID solution works well in ID, but i have the feeling that the scribus UI is still too busy to add even more visual goodies...)

we have a few people skilled in UI and UX (professional graphic designers that do use scribus in their daily work and one UX person) that already have made proposals for scribus. i'll write them an email and ask to comment in this ticket.
if somebody knows other experts that would like to help, just invite them to join the discussion!

**Comment by MrB74** [comment]
I want to see the preview in the drop downs everywhere where it's a font selection. Style preview maybe too.

**Comment by Fahad-Alsaidi** [comment]
Here is what I am proposing for font list in Text properties  
![fontpreview-scribus](https://cloud.githubusercontent.com/assets/1632566/15387714/993de718-1dbf-11e6-88ed-783ca680e9ef.jpg)

**Comment by aoloe** [comment]
fahad, it's nice! i would like that in the font browser.

for the PP i still prefer the way ID is doing.
plain text on the left, fancy display on the right.

**Comment by khaledhosny** [comment]
So here is my take from these screenshots:
- None of them look as cluttered as your font preview.
- They seem to only show one preview text.
- The choice of what script to show seems unclear:
  - Why showing Arabic next to Arial but not Arial Black? Why Arabic, Arial supports a dozen of scripts at least.
- There is a clear separation between the font name and the preview (right aligned, tabulated etc.).

We need to figure this out and have a concrete proposal.

**Comment by khaledhosny** [comment]
Here is my suggestion for choosing the sample text:
- If the font has only one script, show it,
- If it has two scripts and one of them is Latin, show the other,
- If it has more than two scripts and one of them matches the current locale, show it,
- Otherwise don’t show any sample text for the current font at all.

And the sample text should be right aligned (left aligned in RTL locales).

**Comment by Fahad-Alsaidi** [comment]
Well, @khaledhosny you have change you mind about font samples, first you asked about more than one sample and now you are saying one sample. However, your last suggestion is exactly implemented in QFontComboBox Class except the right alignment.

**Comment by khaledhosny** [comment]
I didn’t change my mind, previously I was wondering how many sample should we display, and I genuinely didn’t have an answer. I still prefer no preview at all, but since you and others think otherwise I’m not going to block it, however the UI needs to be usable.

**Comment by MrB74** [comment]
Please also don't forget that in 1.5.4 or 1.5.5 we plan to implement IndigoDock to replace PP.

**Comment by Fahad-Alsaidi** [comment]
Here the latest update:
![scri-font](https://cloud.githubusercontent.com/assets/1632566/15706659/c5cc105c-2805-11e6-8280-3dc0125df142.jpg)

**Comment by Fahad-Alsaidi** [comment]
This is should be fixed now.
