### ISSUE TITLE
Small caps behave wrongly

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#187]
When you click on Small Caps then click it a gain, it will not make text return to its original styles.

**Comment by Fahad-Alsaidi** [comment]
I did bisect and found this problem started from this commit  4bb7e5320e41a262a1a3e7cc2f4d332e6f57bb58

**Comment by khaledhosny** [comment]
I can’t reproduce this.

**Comment by Fahad-Alsaidi** [comment]
It fixed by this commit https://github.com/HOST-Oman/scribus/commit/2284ed70ab2c05760ca5d79d588a4af632a0e4fb
