### ISSUE TITLE
Insert > Ligatures doesn't take the current font in account

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#189]
Can someone reproduce this? 
https://bugs.scribus.net/view.php?id=10718

**Comment by khaledhosny** [comment]
We removed this completely, these “ligatures” are actually legacy Unicode characters whose use is discouraged. We support proper ligatures using smart font features (OpenType, Graphite or even AAT on Mac OS X) which does not need any changes to the underlying text.
