### ISSUE TITLE
Outline text 

### ISSUE THREAD

**Issue by dawoodalbadi** [HOST-Oman/scribus#19]
I couldn't find what commit disturb outline text drawing. Its not correct now.

**Comment by dawoodalbadi** [comment]
I check until this commit 7c0b5dc7c82c84be09556893df55e72b7ad3071f but the problem still there

**Comment by khaledhosny** [comment]
Can you post a screenshot?

**Comment by dawoodalbadi** [comment]
![horn2](https://cloud.githubusercontent.com/assets/9442944/13490814/0a381268-e148-11e5-8606-88511473d88e.png)
