### ISSUE TITLE
Add new styles to styles manager

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#190]
We need to add the new styles (font features, hyphenation, …) styles manager (Edit → Styles).

**Comment by Fahad-Alsaidi** [comment]
From usability point of view, what is the best place for font features setting? under paragraph styles or characters styles?

**Comment by khaledhosny** [comment]
They are character styles, you should be able to apply them to a small part of text or even a single character.

**Comment by Fahad-Alsaidi** [comment]
Here how it will looks for Font Features still WIP
![fontfeatures1](https://cloud.githubusercontent.com/assets/1632566/15532417/c64cf554-2270-11e6-8997-2b2786f0d78b.jpg)

**Comment by Fahad-Alsaidi** [comment]
This is should be fixed now.
