### ISSUE TITLE
Pass GlyphCluster not GlyphLayout to TextLayoutPainter::drawGlyph()

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#191]
This will allow us to address several issues:
- Putting text string to XPS files, instead of the current hack that is broken with any complex text.
- Return the correct character indices in the document checker instead of the current unreliable hack.
- Correctly position tab glyph when show control characters is enabled (we need to know GlyphCluster width), and the correct colour of spaces suppressed at end of line (we need to know GlyphCluster flags).
- Will allow us in the future to output text string in PDF files for accessibility and better text extraction for complex text.

**Comment by Fahad-Alsaidi** [comment]
This should be fixed by https://github.com/HOST-Oman/scribus/commit/5fd80f96afdae738632b142e65a4b2849c36a682
