### ISSUE TITLE
Font features widget should detect what features present in the font

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#192]
Currently there is no indication whether a give feature is available in the font or not. We should query the font for available features for the currently set script and language, and disable the buttons for any feature not available.

**Comment by Fahad-Alsaidi** [comment]
@khaledhosny  Which library that can tell me which  font features supported by any font? Is it Freetype, FontConfig or Harfbuzz ? I am confused between them.

**Comment by khaledhosny** [comment]
HarfBuzz.

**Comment by Fahad-Alsaidi** [comment]
This is should be fixed by 
0ea1cfb5b256ea61796db4b98e1b02ed109474f1
ac32e520dc3c7ff3b099b5422aa6566063c4a4f4
eb7ab6cb29e9577dc0a12fec5081ce35921cb497
