### ISSUE TITLE
DEL key does not work correctly for in-canvas editing

### ISSUE THREAD

**Issue by sommerluk** [HOST-Oman/scribus#196]
Short summary: DEL key does not work correctly for in-canvas editing

Detailed description:

In various cases there are problems with the DEL key when editing the content of text frames within the in-canvas editing (without the story editor). It deletes the wrong characters.

[bug.zip](https://github.com/HOST-Oman/scribus/files/275206/bug.zip)

The attached file contains the following text:

ab́c

U+0061 LATIN SMALL LETTER A
U+0062 LATIN SMALL LETTER B
U+0301 COMBINING ACUTE ACCENT
U+0063 LATIN SMALL LETTER C

Case 1:

Steps to reproduce:

1.) Double-click in the text frame to start in-canvas editing.

1.) Put the text cursor between the grapheme clusters b́ and c.

2.) Press the DEL key on your keyboard.

Expected result: The code point “U+0063 LATIN SMALL LETTER C” is removed. (Like it is the case in the story editor.)

Actual result: The code point “U+0062 LATIN SMALL LETTER B” is removed. So “U+0063 LATIN SMALL LETTER C” is still present and “U+0301 COMBINING ACUTE ACCENT” now shows up above “U+0061 LATIN SMALL LETTER A”.

Case 2:

Steps to reproduce:

1.) Double-click in the text frame to start in-canvas editing.

1.) Put the text cursor between the grapheme clusters a and b́.

2.) Press the DEL key on your keyboard.

Expected result: The grapheme clusters b́ (code points U+0062 LATIN SMALL LETTER B and U+0301 COMBINING ACUTE ACCENT) is removed. (Like it is the case in the story editor.) [Alternatively only the code point U+0062 LATIN SMALL LETTER B could be removed, what might be more useful, but would be inconsistent to the story editor, so the story editor would have to be modified also?]

Actual result: The code point “U+0061 LATIN SMALL LETTER A” is removed.

Further informations:

This is a bug report against the version that is packaged for openSUSE by ftake as 1.5.2ctl.1463526433.3370779-50.1 on Mi 18 Mai 2016 17:59:18 GMT.

**Comment by khaledhosny** [comment]
Looks like a more general issue, even with no combining marks at all the behaviour is buggy.

**Comment by khaledhosny** [comment]
It should be fixed now, please re-open if there are still any issues.
