### ISSUE TITLE
Character counting is wrong for characters outside BMP

### ISSUE THREAD

**Issue by sommerluk** [HOST-Oman/scribus#197]
Short summary: Character counting is wrong for characters outside BMP

Detailed description:

Scribus does not count correctly the characters that are outside of the Basic Multilanguage Plan.

The attached file contains the following text:

🐄

U+1F404 COW

Steps to reproduce:

1.) Right-click in the text frame.

2.) Choose “Information”.

Expected result: The character count is 1.

Actual result: The character count is 2.

Further informations:

This is a bug report against the version that is packaged for openSUSE by ftake as 1.5.2ctl.1463526433.3370779-50.1 on Mi 18 Mai 2016 17:59:18 GMT.

**Comment by sommerluk** [comment]
[bug2.zip](https://github.com/HOST-Oman/scribus/files/275209/bug2.zip)

**Comment by khaledhosny** [comment]
Yes, and there are several other places where character count is wrong as well. I think it is time to bite the bullet and use UTF-32 internally instead of UTF-16.

**Comment by khaledhosny** [comment]
#198 should fix this, but unfortunately you will not be able to use old files containing non-BMP chars as there were saved as individual surrogate pairs (which is invalid). I couldn’t find an easy way to import such invalid characters (the current code reads one charters at a time, so I can’t detect and handle surrogate pairs).

**Comment by khaledhosny** [comment]
This should be fixed now, please test and re-open if things are still broken.

**Comment by Fahad-Alsaidi** [comment]
since we shifted back to utf-16, I reopen this issue.

**Comment by Fahad-Alsaidi** [comment]
This should be fixed by 20ee74d. The other  character count places problems, should be reported individually, so we can track them all.
