### ISSUE TITLE
Fix PDF export

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#2]
The basics work but not feature complete.

**Comment by dawoodalbadi** [comment]
I need testers to test pdf I think it almost finish

**Comment by luzpaz** [comment]
You need testers to test the box branch (https://github.com/HOST-Oman/scribus/tree/boxes) right?

**Comment by dawoodalbadi** [comment]
Yes.
Someone to test text frame and pdf export in boxes branch.

**Comment by dawoodalbadi** [comment]
Should be fixed with 91b14378ddc3fe4809f6e1f259d89c9bd062d928, new issues should be reported separately.
