### ISSUE TITLE
Support for high DPI screens

### ISSUE THREAD

**Issue by zayedalsaidi** [HOST-Oman/scribus#201]
As follow of this thread:
http://lists.scribus.net/pipermail/scribus-dev/2016-May/003076.html

We need to support loading and configure the svg icon set.  The SVG icon set is contributed by Mr. Dezso Markon (will be uploaded latter on). The ideal solution is Scribus follows the desktop settings configuration for the icon size (if they supporting hight DPI in the first place).

**Comment by zayedalsaidi** [comment]
the icon set in svg format is attached. 

[scribus.svg.tar.gz](https://github.com/HOST-Oman/scribus/files/278045/scribus.svg.tar.gz)

**Comment by khaledhosny** [comment]
We will need (preferably in an automated way) to extract the individual icons from this SVG files with the names Scribus expects. We can’t load the icons by id from a single SVG file.

**Comment by zayedalsaidi** [comment]
As svg is xml based format, It is better to extract the ‘g’ element from each object id, then write new svg with the name which is in the inkscape:export-filename tag.

Here is python example:
https://gist.github.com/revolunet/dbe52d5cdf0e38ce35fd

If nobody can do it automatically, I will do it manually.

**Comment by khaledhosny** [comment]
We need the icon file name and its width and height, not sure if the SVG file has all these information. The file also seems to have two sets of icons, so we need to know which elements to extract.

**Comment by zayedalsaidi** [comment]
It seem there is a dark them and a light one but the current used icon set is the light one. However, there are a lot of duplication due to the need to export to different sizes and different names.

I will work to extract all icons manually.

**Comment by zayedalsaidi** [comment]
here is the 202 icons each in a separate  file.
[svg-icons.zip](https://github.com/HOST-Oman/scribus/files/282182/svg-icons.zip)

**Comment by andreas-vox** [comment]
I think this enhanced belongs to trunk, not this branch. Remember that we still have to merge both branches at some point of time...

**Comment by khaledhosny** [comment]
We send such independent enhancements to Scribus bug tracker. The previous
Hi-DPI patches are applied already.

**Comment by Fahad-Alsaidi** [comment]
I think this fixed by now in trunk.
