### ISSUE TITLE
Selecting  is broken in some cases 

### ISSUE THREAD

**Issue by dawoodalbadi** [HOST-Oman/scribus#205]
Hello 
I have noticed that selecting Arabic text will make text disappeared if the text is LTR direction.
If the text in left to right alignment and you try to select a line every thing goes correct 
![screenshot from 2016-06-09 15 29 57](https://cloud.githubusercontent.com/assets/9442944/15928394/a5347048-2e57-11e6-85be-991332ab5c4d.png)

but if you continue to select  the next line 
![screenshot from 2016-06-09 15 30 07](https://cloud.githubusercontent.com/assets/9442944/15928447/f1ad83a6-2e57-11e6-9f3d-718f14a76690.png)
but if you change to right to left every thing goes correct 

![screenshot from 2016-06-09 15 31 19](https://cloud.githubusercontent.com/assets/9442944/15928497/45943884-2e58-11e6-93af-1bbd4fe2326f.png)

also in English if you put RTL direction sam thing will happen

moreover sense I have a large amount of fonts I have test selection in so many fonts and I found out in so many fonts the blue rectangle of selection is on top of the text of previous line

**Comment by Fahad-Alsaidi** [comment]
If you can provide a patch for this will be great.
