### ISSUE TITLE
text relayout unnecessary 

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#214]
the pic below.. on line 8 where all the hs are, there is room to add a few more. When I add another one, the a from the line “er, I am told, very harmless and rather wa” moves to the next line
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/1632566/17544855/d4a3f132-5eea-11e6-938d-6c9ee0f7ea79.png)
the test file:
[TextRenderingTest2.sla.zip](https://github.com/HOST-Oman/scribus/files/410484/TextRenderingTest2.sla.zip)

**Comment by andreas-vox** [comment]
Should be fixed when latest pull request is granted

**Comment by Fahad-Alsaidi** [comment]
fixed by #218
