### ISSUE TITLE
Hyphenation drops

### ISSUE THREAD

**Issue by binyominzeev** [HOST-Oman/scribus#216]
Hello,

I am editing a longer text, on multiple pages, two columns, and on the first few pages hyphenation works fine. However, after the fifth page a strange thing happens: some words are hyphenated correctly, some are randomly, even without a dash, in the middle of the word. And so on it goes, on the pages from this onwards. (Dehyphenating and hyphenating forcefully does not solve the problem.)

I am using Scribus 1.5.3 (svn), complex text layout version, the hyphenated text is in Hungarian.

According to the instructions I received on the mailing list (http://lists.scribus.net/pipermail/scribus/2016-September/053406.html), I am attaching a few examples:

![hyphen-1 5 2](https://cloud.githubusercontent.com/assets/4866177/18419852/717887b0-7864-11e6-8827-355779376c7e.png)
![hyphen-1 5 3](https://cloud.githubusercontent.com/assets/4866177/18419853/71a2e988-7864-11e6-89c8-5d66636a64fb.png)

On the first image it is the older version, with hyphenation working fine, on the second it is broken (for example, fourth line from the bottom of first paragraph, or third line of the second paragraph). Here is the source file:

[hyphen.sla.zip](https://github.com/HOST-Oman/scribus/files/466173/hyphen.sla.zip)

All the best,
Binyomin

**Comment by andreas-vox** [comment]
Is the text still complete and in the right order?

**Comment by andreas-vox** [comment]
Should be fixed when latest pull request is granted

**Comment by binyominzeev** [comment]
Thank you very much, works fine!
