### ISSUE TITLE
Investigate adding  test suit

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#22]
As we do more and more changes to the code chances are high that we will add new regression, even to issues we previously fixed. Without an automated test suit, we are working blindly and one needs to manually test files after each commit which is unpractical and can’t be really enforced.

We should investigate adding an automated testing mechanism (for text frames only for now). There are three kinds of functionality we need to test:
- The actual text layout, independent of the rendering; basically the glyphs,  there positions and other properties. We can handle this by having a special implementation of `TextLayoutPainter` that logs all method invocations in some text format, that we can use for comparing output, something like:

```
drawGlyph: x=0 y=0 gid=5
setFillColor: name=Back shade=100
translate: x=5 y=0
```
- On screen rendering. We can save the output of `ScPainter` to an image (it is already a `QImage`) and use that for comparison, with some tolerance for rasterisation differences.
- PDF (and other export format), we can just export to the desired file and find a way to compare such files to catch any relevant differences.

This all, of course, depends on find away to run Scribus from command line and preferably without opening any windows in a completely automated way.

**Comment by luzpaz** [comment]
CC @QuLogic @sarathms

We've been able to get scribus to run from the CLI 
See
- https://bugs.scribus.net/view.php?id=12572
- https://bugs.scribus.net/view.php?id=238

---

Ref: https://github.com/andreas-vox/ScribusCTL/issues/2

**Comment by luzpaz** [comment]
First Test SLA uploaded in 6e06255223d2c7f2879d5974c11ca07b57f9f015
