### ISSUE TITLE
What is left to merge CTL branch in to Scribus Trunk ?

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#225]
Hey @Fahad-Alsaidi
First, I want to thank you for all your work and for the work of the Host-Oman team did and are doing for Scribus. I'd like to understand better what is left that is necessary to merge CTL in to trunk. 
If you we start a list in this thread or however you feel is most comfortable to indicate what issues are left... that would be great.

- [ ] issue 1
- [ ] issue 2

**Comment by Fahad-Alsaidi** [comment]
@luzpaz There is no major issues should prevent merging CTL into trunk.

**Comment by Fahad-Alsaidi** [comment]
closed
