### ISSUE TITLE
"Show Text Control Characters" prevent CJK characters to be printed on screen

### ISSUE THREAD

**Issue by ftake** [HOST-Oman/scribus#226]
1. input "abcあいう" into a text frame
2. enable "Show Text Control Characters" from document settings
3. the text frame now shows "abcあ  "
[show-text-control-chars.sla.zip](https://github.com/HOST-Oman/scribus/files/587631/show-text-control-chars.sla.zip)
![screenshot_20161113_163359](https://cloud.githubusercontent.com/assets/160235/20244313/cfc74b58-a9bf-11e6-825f-c08515919c92.png)

**Comment by ftake** [comment]
While trying to resolve another bug, I noticed `xoffset` does not cause this strange problem.

```
                                                case SpecialChars::CJK_KANA:
                                                case SpecialChars::CJK_NOTOP:
-                                                       run.extraWidth += quarterEM;
+                                                       run.xoffset += quarterEM;
                                                }
```

**Comment by Fahad-Alsaidi** [comment]
If it fix the problem,  please send PR.

**Comment by ftake** [comment]
Sorry since I have many scribus installed, I was running just a different build.

**Comment by Fahad-Alsaidi** [comment]
by this dd9030459677e8c3646887961baa801624140ea9 , it should be fixed. Please test.

**Comment by ftake** [comment]
thanks. confirmed it is fixed.
