### ISSUE TITLE
Tab indentation other than left-alignment does not work

### ISSUE THREAD

**Issue by ftake** [HOST-Oman/scribus#228]
Tab indentation does not work when its alignment is set to right, center, comma, period.

<img width="570" alt="screenshot_20161117_231308" src="https://cloud.githubusercontent.com/assets/160235/20392754/9ed81508-ad1c-11e6-9f27-c6e22c27803c.png">

**Comment by Fahad-Alsaidi** [comment]
it works with me, could you please write steps how to reproduce the bug?

**Comment by ftake** [comment]
A problematic file is attached. The screnshot above is one of SVN trunk (a few weeks ago).
The position of text on SVN version is also something wrong too.

<img width="371" alt="screenshot_20161120_213704" src="https://cloud.githubusercontent.com/assets/160235/20462823/d3c0180c-af69-11e6-80bc-0ccd87ae349b.png">
[tab.sla.zip](https://github.com/HOST-Oman/scribus/files/602004/tab.sla.zip)

**Comment by Fahad-Alsaidi** [comment]
@ftake  without steps how to reproduce the bug I couldn't figure out how the bug is triggered. Right now, in the attached file, tab width is saved in it and scribus just read it from there directly.

**Comment by ftake** [comment]
> tab width is saved in it and scribus just read it from there directly.

If so, I cannot understand why the layout results of the same file are different between CTL branch (below) and SVN version (above).

Anyway here are the steps to reproduce.
1. Add text frame and set its font to appropriate one (Noto Sans, here)
2. Input "pen`TAB`pineapple`Enter`apple`Tab`pen"
3. `Ctrl+A` to select all paragraph
3. Set tab position by clicking the ruler and now "pineapple" and "pen" are aligned their left.
4. Right click the tab position several times and toggle alignment modes.

Expected result:
- "pineapple" and "pen" are aligned right, center, ...

Actual result:
- the alignment does not change and keep "left"

**Comment by Fahad-Alsaidi** [comment]
Now I can see the problem. However, it aligns left , centre and right for
the first time but the second time does not work. Am I right?

**Comment by ftake** [comment]
On my environment, they do not work every time...

**Comment by Fahad-Alsaidi** [comment]
@ftake after more inspection, it seems it works fine with me. 
![anim](https://cloud.githubusercontent.com/assets/1632566/20608644/1206a2e4-b29d-11e6-915e-202752285979.gif)

**Comment by ftake** [comment]
Well..., you are only testing left tab alignment.
Why don't you right click tab position mark to switch to right alignment?

**Comment by Fahad-Alsaidi** [comment]
Here we go:
![anim](https://cloud.githubusercontent.com/assets/1632566/20631453/060d4f7a-b350-11e6-8318-d5a2443225dd.gif)

**Comment by ftake** [comment]
So it does not work right?
The expected result is like the above window on the screen shot.

**Comment by ftake** [comment]
Here is layout result in LibreOffice.

The reversed "L" means right alignment. The tab width is extended so that the end of next parts (before next tab or end of line) is a line.
![right](https://cloud.githubusercontent.com/assets/160235/20632130/969ba75c-b37e-11e6-8008-e2611c64cc1e.png)

The reversed "T" means center alignment. The tab width is extended so that the next parts align with their center.
![center](https://cloud.githubusercontent.com/assets/160235/20632131/96a313c0-b37e-11e6-88b0-7bbbb9c6a9d5.png)

These features on Scribus is broken on this CTL branch.

**Comment by Fahad-Alsaidi** [comment]
@ftake thanks. It is my first time to know this feature, even in LibreOffice.

**Comment by Fahad-Alsaidi** [comment]
after a long bisect session, I found the problematic commit. by b2ed6be4f392449172b75bfed1275e6876a6981d, the old behavior should be restored. please test.

**Comment by ftake** [comment]
Now working. Thanks!
