### ISSUE TITLE
bullet list is broken

### ISSUE THREAD

**Issue by ftake** [HOST-Oman/scribus#229]
[bullet-list.sla.zip](https://github.com/HOST-Oman/scribus/files/602027/bullet-list.sla.zip)
<img width="288" alt="screenshot_20161120_212459" src="https://cloud.githubusercontent.com/assets/160235/20463067/803d9fc4-af6e-11e6-8377-b35a19f8c5b2.png">

**Comment by Fahad-Alsaidi** [comment]
by e0a850cddd0f5664047d259f2484deb88b4956f0, it should be fixed. Please test.

**Comment by ftake** [comment]
Thank you. It works.
