### ISSUE TITLE
Hebrew issues

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#231]
Per issue: [#14154](https://bugs.scribus.net/view.php?id=14154)
This is the result I get using the latest working appimage (e0a850cddd0f5664047d259f2484deb88b4956f0)
![hebrew-rtl](https://cloud.githubusercontent.com/assets/4140247/20613550/1c2acc28-b293-11e6-9bac-c87b9aa8a754.png)
Test File: [Test_hebrew.sla.zip](https://github.com/HOST-Oman/scribus/files/612445/Test_hebrew.sla.zip)

Edit: 
1st box is correct  
2nd box is incorrect  
3rd box is incorrect

**Comment by Fahad-Alsaidi** [comment]
@luzpaz please notice that mirror thing has been removed from CTL branch because it is completely wrong. So don't use it, it will change the text to wrong order. RTL mirror  doesn't compatible with CTL branch.

**Comment by luzpaz** [comment]
Ok. Good to know

**Comment by Fahad-Alsaidi** [comment]
closed!

**Comment by MrB74** [comment]
This needs reopening, but in a different context. We want mirroring capability, but not for text layout as such. Eg for writing mirrored text. We'd even want that for CTL. Eg, you know when someone prints something that is expected to be read in a mirror.

**Comment by MrB74** [comment]
This can stay closed. the Flip horizontal function will do. #234 is open now though for cursor placement.

**Comment by aoloe** [comment]
(copied and adapted into #234)

@MrB74 do we really need to support this use case?
is there any "legit" use for it in DTP? (except having some fun... which is legit and can be done... see below)

I know that somebody might want to write "ɘɔnɒludmɒ" on her car, but i wonder if scribus is the right tool for such jobs...

IMO if somebody wants to mirror some text, she can convert it to vectors and mirror it. that should be enough.

currently, this feature seems to be deceiving our users more than helping them to achieve their goals...

**Comment by MrB74** [comment]
No, we want this feature in Scribus. Its a perfectly legitimate use case. I’ve even seen reversed text in any document, like magazines.
