### ISSUE TITLE
Bullet and number list: layout just after setting list is wrong

### ISSUE THREAD

**Issue by ftake** [HOST-Oman/scribus#232]
When a file contains bullet list and/or number list,
- positions of new line symbols at the end of list are wrong
- numbers of a number list are shown as "?"

This problem happen by making a new bullet list or numbered list.

By adding some characters into the frame containing those lists, the layout of them are calculated to the correct position.
![list-2016-11-26_13 49 46](https://cloud.githubusercontent.com/assets/160235/20638157/88caa3a4-b3e1-11e6-8589-6e742ca4c726.gif)

## Steps to reproduce (bullet)
0. enable to show control characters
1. insert the following lines into an empty text frame
```
pen
pineapple
apple
pen
```
2. select all lines and set bullet list from the paragraph effect setting

## Steps to reproduce (number)
1. insert the following lines into an empty text frame
```
pen
pineapple
apple
pen
```
2. select all lines and set numbered list from the paragraph effect setting

**Comment by Fahad-Alsaidi** [comment]
by af8b3f130c780c0dfc555e20803cb4629103f2e6, it should be fixed.

**Comment by ftake** [comment]
Not fixed to me
<img width="727" alt="screenshot_20161127_222156" src="https://cloud.githubusercontent.com/assets/160235/20648685/1fbd2e2a-b4f1-11e6-800a-9b3ce92296dc.png">

**Comment by Fahad-Alsaidi** [comment]
check now after this 58f2c29859474285419569dab7dffd69cc4a8067

**Comment by ftake** [comment]
The fix works for the file attached above.

However, there is a file that is still broken. I am investigating how can I reproduce this with a new file.
I think af8b3f1 is problematic since the PDF (show at the left) is generated by the previous commit of af8b3f1

![default](https://cloud.githubusercontent.com/assets/160235/20677524/af4d049e-b5d6-11e6-8c17-f6b7985ca94e.png)

**Comment by Fahad-Alsaidi** [comment]
That commit was really a problematic and solve one part of general issue.
To be frank, the structure of marks in scribus is a mess specially bullet
and number list. It needs refactoring and fit in current  boxes design.

**Comment by Fahad-Alsaidi** [comment]
I pushed a new commit d826277b8104b4ef935bdfe718dba1b5175db8f9, please test.

**Comment by ftake** [comment]
That fix looks good.
After opening a file, I noticed a bullet list slightly moves (the space between a bullet and the first line shrinks) when I double clicked the text frame containing it.

I am not sure the reason is that the file is saved by a problematic version of Scribus or not.

**Comment by Fahad-Alsaidi** [comment]
well, if the bug is solved, I will close it. If you have another bug relate to it, please open a new bug.
