### ISSUE TITLE
glyph color not used

### ISSUE THREAD

**Issue by JLuc** [HOST-Oman/scribus#235]
importing a 1.5.3 non-ctl document, i see all glyph colors get displayed black
see uploaded document (i had to rename it to txt so it gets uploaded)

[pa coul puces.sla.txt](https://github.com/HOST-Oman/scribus/files/626960/pa.coul.puces.sla.txt)

**Comment by JLuc** [comment]
On other documents, glyph colors are not black but are not correct.
And sometimes they are correct also.

**Comment by luzpaz** [comment]
@JLuc FYI you can always .zip and then upload your attachement

**Comment by JLuc** [comment]
oh sure :-)

**Comment by Fahad-Alsaidi** [comment]
Does this happen when you import non-ctl document (1.5.3 or less ) ? what about  if you color the glyph in CTL and open it again it will works?

**Comment by JLuc** [comment]
Yes as reported previously this happens when i import non-ctl document.
Best is probably when you try the uploaded document for yourself.

On the uploaded document  : 
- it happens on all unicode  glyphs (displayed in Webding font) and when i change the color, display doesnt update.
- when i change the color of another glyph display is updated correctly.

On other non-ctl documents it affects also some parts of texts using 'normal ascii' glyphs, but they dont appear black, but in another color, different then the color that should be.

**Comment by JLuc** [comment]
copied with more color issues into mantis https://bugs.scribus.net/view.php?id=14424

**Comment by luzpaz** [comment]
Fix applied in r21603 
mirrored -> https://github.com/scribusproject/scribus/commit/0eb4b9d528762d20c74770ede55ddb02d34ed3d8

**Comment by MrB74** [comment]
This can be closed
