### ISSUE TITLE
vague reports

### ISSUE THREAD

**Issue by JLuc** [HOST-Oman/scribus#236]
vague reports of features not working correctly in CTL.
So as to remember before deepening or vorgeting 
and maybe get feedback.

**Comment by JLuc** [comment]
When importing a non-CTL 153 document , page number get displayed twice in a row.
Instead of 5 one sees 55 

AMOF strangest is that in the SLA, there is     
```
  <var name="pgno" CPARENT="Pagination"/>
  <var name="pgno" CPARENT="Pagination"/>

```
These double pgno were allready there in original file, but were not displayed, when they are with CTL.

So however the issue might be not in CTL but in non-CTL, CTL might smartly correct these double when importing ?

Trying to create a simple document displaying the issue, at some point non-CTL version also displays the pageno as double. So i cant provide a clear test case yet.

EDIT : i could create a simple test document and this is now #237

**Comment by JLuc** [comment]
Layout is not the same.
More lines get in the page.

**Comment by JLuc** [comment]
Some document settings might be different, like "autosave doc" and "display autosave clock" (but this might be related to previous months autosave feature ?)

**Comment by khaledhosny** [comment]
> Layout is not the same.
> More lines get in the page.

That would be an expected consequence of using font features like kerning or ligatures.

**Comment by Fahad-Alsaidi** [comment]
close for now. follow discussion in #237.

**Comment by JLuc** [comment]
So you prefer me to open lots of bugs with vague reports rather than having one single vague report and gather there all loosely described issues before being able to creating a precise issue ?

**Comment by JLuc** [comment]
beside, you have closed that report without fixing the issues...

if you prefer so you can ask me to wait merge into trunk before testing and creating mantis reports !
if so, please ask and i'll be happy to stop loosing my time on your tracker

**Comment by Fahad-Alsaidi** [comment]
@JLuc How can I fix a problem if it is vague? There is no way to reproduce it. I encourage you and anyone else to submit bugs but please help me to help you. The other bug you mention, it is not a bug and the code works as expected even though we have not touched that part of code and it is out of CTL scope. However,  I don't have plan yet after merging CTL into scribus, thus it is better to fill your bugs into scribus bug tracking system. 
Finally, I am sorry to loose your time here.

**Comment by JLuc** [comment]
This report was a "dont forget notes for future reports"

i see the merge has happened so i'll go toward trunk mantis
