### ISSUE TITLE
Ugly text in screen !!

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#38]
I pull latest commit 0afaf8f4e4e6d1628b43c47fcae8161c6fc7eb79 , the text in screen is very ugly & some numbers and characters are missing such as E & A.
![scribus](https://cloud.githubusercontent.com/assets/1632566/13700922/68606dbc-e79d-11e5-801f-104564f518a8.jpg)

**Comment by khaledhosny** [comment]
There are some mysterious interaction between Scribus, FreeType and Cairo. I have been debugging this all weekend and it is going nowhere!

**Comment by khaledhosny** [comment]
This should be fixed with 8a7f863d2414b1389d32c8dc570ac417b2a8eb46 and 854fe8f7154ca9411044ebbcefefd536498eb978, please check.

**Comment by Fahad-Alsaidi** [comment]
I confirm the fix. Thanks
