### ISSUE TITLE
Fix ScPainter::drawText()

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#69]
It uses Cairo’s toy text API and does not support complex text layout. We need to find where it is used and if it is worth the non-trivial amount of work needed to fix it.

**Comment by Fahad-Alsaidi** [comment]
Test file [render-frame.sla.gz](https://github.com/HOST-Oman/scribus/files/206080/render-frame.sla.gz)

**Comment by khaledhosny** [comment]
Fixed in #149.
