### ISSUE TITLE
Fix path text

### ISSUE THREAD

**Issue by dawoodalbadi** [HOST-Oman/scribus#7]
Path text does not currently work.

**Comment by khaledhosny** [comment]
I pushed a simple change that makes path text work again on screen, PDF does not show anything, though.

**Comment by khaledhosny** [comment]
Here is a test file [pathtext.zip](https://github.com/HOST-Oman/scribus/files/158180/pathtext.zip):
![2016-03-04 09-55-54](https://cloud.githubusercontent.com/assets/93914/13519239/1e7759e4-e1ef-11e5-9767-963134d4877e.png)

**Comment by dawoodalbadi** [comment]
That a quite easy solution,  in pdf we will need to return back some functionalities of set text string and set text char. It need to have a check to check if this is path text do something if not call text layout render. I was working on creating a boxes and a new painter for path text but I don’t know where that will take me. I think I will discard my work and continue to work according to your proposal and make it happen for pdf.

**Comment by khaledhosny** [comment]
I tried recovering some of the old setTextCh and setTextSt code and it works, but no text is shown because used fonts are empty and that is because the new code for populating used fonts does not take path text into account. At this stage I think it is actually simpler to continue with the boxes plane, otherwise we will have to keep a lot of old code just for path text.

**Comment by dawoodalbadi** [comment]
hello 
@khaledhosny  I got problem on constructing new boxes because they need Glyph run and I tried to construct glyph run depending on the glyphs layout that you create them in path text. I couldn't understand how I can do that with all these changes in the glyph runs.

**Comment by khaledhosny** [comment]
See https://github.com/HOST-Oman/scribus/blob/boxes/scribus/pageitem_textframe.cpp#L1365-L1386

**Comment by khaledhosny** [comment]
Should be fixed now.
