### ISSUE TITLE
Add RTL & LTR direction in Story Editor 

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#81]
Right now text frame has RTL & LTR direction but not yet in story editor.

**Comment by luzpaz** [comment]
Related to [6004](https://bugs.scribus.net/view.php?id=6004) ?

> wishlist: set default Text Area's content direction to rtl

**Comment by khaledhosny** [comment]
Does not seems so (and the fact that anyone though the R button can be of any use for RTL text just blows my mind).

**Comment by Fahad-Alsaidi** [comment]
The idea is good but you need also preset the font name to make it useful.

**Comment by Fahad-Alsaidi** [comment]
The commit by @ShamsaHamed  has a small bug. When you click RTL button the text in story editor align as LTR and the opposite is right.

**Comment by ShamsaHamed** [comment]
That's what I was said last time, the same bug with right/left alignment
Button's, it do the same.
You said no matter how it appear in the story editor.

**Comment by Fahad-Alsaidi** [comment]
@ShamsaHamed right now the RTL & LTR buttons do set the style but also change story editor alignment. Thus for consistency, please fix it.

**Comment by khaledhosny** [comment]
On my system the alignment is correct, so I though @ShamsaHamed somehow figured how to handle it. My guess would be that Qt is trying to over-smart us somehow and consider left align an synonymous to “align to start of text” and vice versa, so it changes its meaning based on text direction.
