### ISSUE TITLE
Set BidiLevel  in XPS export

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [HOST-Oman/scribus#83]
XPS support BidiLevel attributes for text, so we should add it.

**Comment by luzpaz** [comment]
Just a heads up that if you're testing this bug, in the bugtracker recently this ticket was created: "XPS export of Text is broken." [13852](https://bugs.scribus.net/view.php?id=13852) 
Franz writes: 

> Update: further investigation shows that text export is only broken when you use Okular as a viewer. Other viewers like gxps display text correctly. Okulars failure may be caused by the missing "UnicodeString" attribute in the "Glyphs" tag. 

I made a notation in the ticket https://bugs.scribus.net/view.php?id=13852#c39452

**Comment by khaledhosny** [comment]
We probably should tackle this as a general issue with outputting original text stream in output formats that support it (e.g. UnicodeString in XPS and ActualText in PDF). I had this on my list for CTL issues to implement, but I’m not sure we will get to it in the first phase. However Okular not showing the glyphs is really their bug, and it probably means it can’t handle complex text properly.

**Comment by luzpaz** [comment]
Scribus ticket [13852](https://bugs.scribus.net/view.php?id=13852)  has been fixed by Franz. 
See:
680c904a8a8d2a85d774bb6ecf59e314398b49f2
12ef2d5ad4977010311399cd08045bec44d4b56b
ac4a381e242b304b248872c8d453552d9e63f81b
25648d11c4d7607fc971136f17026f02409959ff

**Comment by khaledhosny** [comment]
https://github.com/HOST-Oman/scribus/commit/12ef2d5ad4977010311399cd08045bec44d4b56b is completely wrong and will not work with most complex scripts, if it were that easy we would have done it!

**Comment by luzpaz** [comment]
I let Franz know via [13852](https://bugs.scribus.net/view.php?id=13852)

**Comment by khaledhosny** [comment]
I outlined in #119 how I think this should be done.

**Comment by Fahad-Alsaidi** [comment]
XPS export is broken now !!

**Comment by luzpaz** [comment]
Forgot to mention: Franz responded:

> This fix is not meant to be perfect. Its a hack, only other way would be to extend the GlyphLayout structure. And for complex scripts we have to change the XPS Text export anyways. 

So we just need to make a note that this ticket (and commits related to it) needs to be reconciled in CTL

**Comment by Fahad-Alsaidi** [comment]
This should be fixed by https://github.com/HOST-Oman/scribus/commit/5fd80f96afdae738632b142e65a4b2849c36a682
