### ISSUE TITLE
Numbered lists are not working correctly

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#91]
The prefix and suffixes often get in the same side, and the numbers (e.g. 10 or 12) are RTL when the text is RTL but they should always be LTR.

[numeration-rtl.sla.gz](https://github.com/HOST-Oman/scribus/files/187776/numeration-rtl.sla.gz)

**Comment by khaledhosny** [comment]
cc @dawoodalbadi.

**Comment by dawoodalbadi** [comment]
I think you fix this in some point. I cant generate the problem any more.

**Comment by khaledhosny** [comment]
Seems so, closing for now.
