### ISSUE TITLE
Dotted circle with Malayalam text

### ISSUE THREAD

**Issue by khaledhosny** [HOST-Oman/scribus#95]
Create an empty text frame, go to https://translate.google.com/#auto/ml/Hello%20World, copy the text to the frame and change the font to Noto Sans Malayalam: text will show some dotted circles. Change the alignment to right align and back and they will disappear.

I suspect this is not specific to Malayalam and might be a general issue.

**Comment by Fahad-Alsaidi** [comment]
I can't reproduce it. 
![malayalam](https://cloud.githubusercontent.com/assets/1632566/14063770/2e54cd92-f3f1-11e5-9fed-084edb57ed77.jpg)

**Comment by khaledhosny** [comment]
Seems to be have fixed itself. Self-healing code is the best.
